id: IC4148871
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T14:15:29+00:00'
last_modified: '2022-06-08T07:51:09.874556+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13115
  title: རྒྱུད་བཞི། ༼ལྕགས་པོ་རི་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A441:
      image_group_id: I1KG13487
      title: ''
      total_pages: 740
      order: 1
      base_file: A441.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
